name: Notify on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send notification email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com # Altere se usar outro serviço de e-mail
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }} # Adicione seu e-mail como segredo
          password: ${{ secrets.EMAIL_PASSWORD }} # Adicione sua senha de e-mail como segredo
          subject: 'Novo Push para o Repositório!'
          body: 'Um novo push foi feito no branch main do repositório ${GITHUB_REPOSITORY}.'
          to: 'seu-email@exemplo.com' # Substitua pelo seu e-mail
          from: 'seu-email@exemplo.com' # Substitua pelo seu e-mail
