name: Notify on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.your-email-provider.com  # Altere para o servidor SMTP que você está usando
          server_port: 587  # Altere para a porta do seu servidor SMTP
          username: ${{ secrets.EMAIL_USERNAME }}  # Segredo para o e-mail
          password: ${{ secrets.EMAIL_PASSWORD }}  # Segredo para a senha
          subject: 'Novo Push no Repositório'
          body: 'Um novo push foi feito no repositório.'
          to: 'seu-email@exemplo.com'  # O e-mail para o qual você deseja enviar a notificação
          from: ${{ secrets.EMAIL_USERNAME }}  # E-mail do remetente
